"""Add alternate draft artwork

Revision ID: 7ade4fc77f8f
Revises: adae1f0f1792
Create Date: 2026-09-22 21:29:15.348833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ade4fc77f8f'
down_revision = 'adae1f0f1792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_hover_path', sa.String(length=240), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.drop_column('cover_hover_path')

    # ### end Alembic commands ###
