"""Create library, access, progress and audit tables

Revision ID: adae1f0f1792
Revises:
Create Date: 2026-09-22 09:53:08.050345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adae1f0f1792'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('oidc_subject', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('first_login_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('membership_status', sa.String(length=32), nullable=False),
    sa.Column('membership_checked_at', sa.DateTime(), nullable=True),
    sa.Column('membership_scope', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('oidc_subject', name=op.f('uq_user_oidc_subject')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_user_telegram_id'))
    )
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('subtitle', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_path', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('access_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('completion_percent', sa.Integer(), nullable=True),
    sa.CheckConstraint("access_type IN ('free','fragment','subscriber')", name=op.f('ck_work_work_access')),
    sa.CheckConstraint("status IN ('draft','ongoing','completed')", name=op.f('ck_work_work_status')),
    sa.CheckConstraint('completion_percent IS NULL OR (completion_percent >= 0 AND completion_percent <= 100)', name=op.f('ck_work_work_completion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work')),
    sa.UniqueConstraint('slug', name=op.f('uq_work_slug'))
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('fragment_body', sa.Text(), nullable=False),
    sa.Column('body_format', sa.String(length=16), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=16), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("access_type IN ('free','fragment','subscriber')", name=op.f('ck_chapter_chapter_access')),
    sa.CheckConstraint("body_format IN ('markdown','html')", name=op.f('ck_chapter_chapter_format')),
    sa.CheckConstraint('number >= 0', name=op.f('ck_chapter_chapter_number')),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], name=op.f('fk_chapter_work_id_work')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter')),
    sa.UniqueConstraint('work_id', 'number', name=op.f('uq_chapter_work_id')),
    sa.UniqueConstraint('work_id', 'slug', name=op.f('uq_chapter_work_id'))
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_work_id'), ['work_id'], unique=False)

    op.create_table('local_login_ticket',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_local_login_ticket_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_login_ticket'))
    )
    op.create_table('fingerprint_receipt',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('fk_fingerprint_receipt_chapter_id_chapter')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_fingerprint_receipt_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fingerprint_receipt'))
    )
    op.create_table('read_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=180), nullable=False),
    sa.Column('route', sa.String(length=260), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('fk_read_audit_chapter_id_chapter')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_read_audit_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_read_audit'))
    )
    with op.batch_alter_table('read_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_read_audit_created_at'), ['created_at'], unique=False)

    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.String(length=24), nullable=False),
    sa.Column('scroll_position', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('fk_reading_progress_chapter_id_chapter')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_reading_progress_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_progress')),
    sa.UniqueConstraint('user_id', 'chapter_id', name=op.f('uq_reading_progress_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_progress')
    with op.batch_alter_table('read_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_read_audit_created_at'))

    op.drop_table('read_audit')
    op.drop_table('fingerprint_receipt')
    op.drop_table('local_login_ticket')
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_work_id'))

    op.drop_table('chapter')
    op.drop_table('work')
    op.drop_table('user')
    # ### end Alembic commands ###
